mode: easy_04
plan_list:
- - -11.41
  - 56.82
  - -0.30
  - -3.1207963267948964
  - 4
  - "2024_04_22_10_35_34"
  - RLAttackPlanner
  - {}
load_HD_map: false
start_euler:
- 0.0
- 0.0
- 0.0
start_ab:
- 0.0
- 0.0
start_velo: 1
start_steer: 0
scene_name: "1179959"
iteration: 30000